# Generated by Django 2.1 on 2018-09-06 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('gender', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('x', 'Misto')], max_length=2, verbose_name='Sexo')),
                ('kind', models.CharField(choices=[('1', 'República'), ('2', 'Pensionato/Casa de família'), ('3', 'Kitnet/Flat'), ('4', 'Apartamento ou casa para dividir'), ('5', 'Imovél para locação do tipo casa'), ('6', 'Imovél para locação do tipo apartamento')], max_length=3, verbose_name='Tipo de imóvel')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('contact', models.TextField(verbose_name='Contato')),
                ('details', models.TextField(verbose_name='Detalhes')),
                ('latitude', models.CharField(max_length=200, verbose_name='')),
                ('longitude', models.CharField(max_length=200, verbose_name='')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
