# Generated by Django 2.1 on 2018-08-29 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('x', 'Misto')], max_length=2)),
                ('tipo', models.CharField(choices=[('1', 'República'), ('2', 'Pensionato/Casa de família'), ('3', 'Kitnet/Flat'), ('4', 'Apartamento ou casa para dividir'), ('5', 'Imovél para locação do tipo casa'), ('6', 'Imovél para locação do tipo apartamento')], max_length=3)),
                ('endereco', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('contato', models.TextField()),
                ('detalhes', models.TextField()),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('aprovado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
